// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCFRQUJpY-9oMRMP5f1Dfni-4ceWl4vLM',
    appId: '1:189042231626:web:b0e534e77ddcbacac219b3',
    messagingSenderId: '189042231626',
    projectId: 'nasa-hackathon-98d21',
    authDomain: 'nasa-hackathon-98d21.firebaseapp.com',
    storageBucket: 'nasa-hackathon-98d21.appspot.com',
    measurementId: 'G-M8DHSBSZWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9m6ydO0ufnt8QvKQRW_JBEIobteplLCM',
    appId: '1:189042231626:android:66c5f6660a219653c219b3',
    messagingSenderId: '189042231626',
    projectId: 'nasa-hackathon-98d21',
    storageBucket: 'nasa-hackathon-98d21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNwYmyOAmEhf7cn7rrnsy8qQzA8H0PCM8',
    appId: '1:189042231626:ios:fd4a5e7370827688c219b3',
    messagingSenderId: '189042231626',
    projectId: 'nasa-hackathon-98d21',
    storageBucket: 'nasa-hackathon-98d21.appspot.com',
    iosBundleId: 'com.gmail.yp10731155',
  );
}
